### ISSUE TITLE
Provide API that doesn't require using reflection inside

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/hrw#16]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see reflection in the code. Especially in performance-critical parts of the code.

## Describe the solution you'd like
Get rid of reflection. I'd suggest making a v2 version of the library.

## Describe alternatives you've considered
Not a lot of them.

**Comment by carpawell** [comment]
No v2 release yet but a generic version was merged: https://github.com/nspcc-dev/hrw/pull/19.
