### ISSUE TITLE
`murmur3` external dep is not maintained (at least it seems so)

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/hrw#17]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see using libraries that have not gotten any patches for years (well, they _could be_ good enough but let me be a pessimist). https://github.com/spaolacci/murmur3 is one of them, it got its last commit at the same time we changed our library, wow!

## Describe the solution you'd like
See if we have any other examples to test or even bench, e.g. https://github.com/twmb/murmur3.

## Describe alternatives you've considered
Do nothing.

## Additional context
I went through go.mod and this repo does not use this many deps to skip the fact that `murmur3` has not been updated for 3+ years.

**Comment by roman-khimov** [comment]
NeoGo uses github.com/twmb/murmur3 v1.1.5, so it should be OK, but please check wrt performance differences.
